stages:
- stage: Deploy
  jobs:
  - deployment: DeployJob
    displayName: Deploy to Environment
    environment: 'ENV_02_21_22' # Replace with your environment name
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Deploying to environment"
